[package]
name = "maidono"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0", features = ["tls", "json"] }
toml = "0.8.12"
maidono_core = { path = "../core" }