[package]
name = "maidctl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
maidono_core = { path = "../core" }
